version: "3"

# Access site at http://${NAME}.dev
# Point search_api_solr to http://${NAME}-solr:8983/solr/#/drupal

services:

  php:
    image: wodby/drupal-php:${PHP_TAG}
    container_name: ${NAME}-php
    environment:
      PHP_DOCROOT: ${DOCROOT} # Relative path inside the /var/www/html/ directory.
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog.develop:1025
      PHP_FPM_MAX_CHILDREN: 16
      PHP_MAX_EXECUTION_TIME: 3600
      PHP_MEMORY_LIMIT: 512M
#      PHP_XDEBUG: 0
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG_REMOTE_AUTOSTART: 1
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0         # This is needed to respect remote.host setting
      PHP_XDEBUG_REMOTE_HOST: host.docker.internal
      PHP_XDEBUG_MAX_NESTING_LEVEL: 2048
      PHP_IDE_CONFIG: serverName=${NAME}.develop
    volumes:
#      - ./:/var/www/html:delegated
      - docker-sync:/var/www/html:nocopy
    external_links:
      - mysql
    networks:
      - default
      - common-apps_default

  nginx:
    image: wodby/nginx:1.15-5.3.3
    container_name: ${NAME}-nginx
    environment:
      VIRTUAL_HOST: ${NAME}.develop
      NGINX_BACKEND_HOST: ${NAME}-php
      NGINX_SERVER_ROOT: /var/www/html/${DOCROOT}
      NGINX_VHOST_PRESET: drupal8
    volumes:
#      - ./:/var/www/html:delegated
      - docker-sync:/var/www/html:nocopy
    labels:
      - 'traefik.backend=${NAME}-nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:${NAME}.develop'
    depends_on:
      - php
    networks:
      - default
      - common-apps_default

  mariadb:
    image: wodby/mariadb:10.1
    container_name: ${NAME}-db
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-sync:/var/lib/mysql:delegated
    ports:
      - "3313:3306"
    labels:
      - 'traefik.backend=${NAME}-db'
      - 'traefik.port=3313'
      - 'traefik.frontend.rule=Host:${NAME}-db.develop'
    networks:
      - default
      - common-apps_default

  memcached:
    image: wodby/memcached:1.5-2.1.1
    container_name: ${NAME}-memcached
    command: ['-m', '512m']

networks:
  common-apps_default:
    external: true

volumes:
  docker-sync:
    external:
      name: "${NAME}-sync"
  mysql-sync:
    external:
      name: "${NAME}-db-sync"
