version: "3"

# Access site at http://${NAME}.dev
# Point search_api_solr to http://${NAME}-solr:8983/solr/#/drupal

services:

  php:
    image: wodby/drupal-php:7.2-dev-macos
    container_name: seanb_php
    environment:
      PHP_DOCROOT: web
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog.develop:1025
      PHP_FPM_MAX_CHILDREN: 16
      PHP_MAX_EXECUTION_TIME: 3600
      PHP_MEMORY_LIMIT: 512M
#      PHP_XDEBUG: 0
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG_REMOTE_AUTOSTART: 1
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0         # This is needed to respect remote.host setting
      PHP_XDEBUG_REMOTE_HOST: host.docker.internal
      PHP_XDEBUG_MAX_NESTING_LEVEL: 2048
      PHP_IDE_CONFIG: serverName=seanb.develop
    volumes:
      - ./:/var/www/html:delegated
    external_links:
      - mariadb
    networks:
      - default
      - common-apps_default

  nginx:
    image: wodby/drupal-nginx:8-1.15
    container_name: seanb_nginx
    environment:
      VIRTUAL_HOST: seanb.develop
      NGINX_BACKEND_HOST: seanb_php
      NGINX_SERVER_NAME: seanb.develop
      NGINX_SERVER_ROOT: /var/www/html/web
    volumes:
      - ./:/var/www/html:delegated
    labels:
      - 'traefik.http.routers.seanb_nginx.rule=Host(`seanb.develop`)'
    depends_on:
      - php
    networks:
      - default
      - common-apps_default

  mariadb:
    image: wodby/mariadb:10.1
    container_name: seanb_db
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./.mysql-data:/var/lib/mysql:delegated
    ports:
      - "3313:3306"
    labels:
      - 'traefik.http.routers.eur_nginx.rule=Host(`seanb-db.develop`)'
    networks:
      - default
      - common-apps_default

  memcached:
    image: wodby/memcached:1.5-2.1.1
    container_name: seanb_memcached
    command: ['-m', '512m']

networks:
  common-apps_default:
    external: true
