version: "2"

# Access site at http://${NAME}.dev
# Point search_api_solr to http://${NAME}-solr:8983/solr/#/drupal

services:

  php:
    image: wodby/drupal-php:${PHP_WODBY_TAG}
    environment:
      PHP_DOCROOT: ${DOCROOT} # Relative path inside the /var/www/html/ directory.
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog.develop:1025
      PHP_FPM_MAX_CHILDREN: 16
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1              # Renamed from PHP_XDEBUG_ENABLED in latest version.
      PHP_XDEBUG_REMOTE_AUTOSTART: 1            # Renamed from PHP_XDEBUG_AUTOSTART in latest version.
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0         # This is needed to respect remote.host setting bellow
      PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"  # You will also need to 'sudo ifconfig lo0 alias 10.254.254.254'
      PHP_XDEBUG_MAX_NESTING_LEVEL: 2048
      PHP_IDE_CONFIG: serverName=${NAME}.develop
    volumes:
      - ./:/var/www/html:delegated
    external_links:
      - mysql
      - dockerdns
    networks:
      - default
      - common-apps_default
    dns:
     - ${DOCKERDNS}

  nginx:
    container_name: ${NAME} # without .develop if using .develop dns
    image: wodby/drupal-nginx:8-1.13
    environment:
      VIRTUAL_HOST: ${NAME}.develop # This tell global proxy about this container.
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_NAME: ${NAME}.develop
      NGINX_SERVER_ROOT: /var/www/html/${DOCROOT}
      DRUPAL_VERSION: ${DRUPAL_VERSION}  # Allowed: 7, 8.
    volumes:
      - ./:/var/www/html:delegated
    depends_on:
      - php
    networks:
      - default
      - common-apps_default

networks:
  common-apps_default:
    external: true
